const palette = {
  black: '#0A0A0F',
  darkSurface: '#13131A',
  surface: '#1C1C2A',
  surfaceElevated: '#252535',
  border: '#2E2E42',
  borderLight: '#3A3A52',
  primary: '#FF6B9A',
  primaryAlt: '#FF8E53',
  roseGold: '#D4877A',
  coral: '#FF6B9A',
  lavender: '#9B8EC4',
  text: '#F0EEF6',
  textSecondary: '#9B99AA',
  textMuted: '#6B6880',
  white: '#FFFFFF',
  danger: '#FF4757',
  success: '#2ED573',
  lightBg: '#F8F8FA',
  lightSurface: '#FFFFFF',
  lightBorder: '#E8E6F0',
  lightText: '#1A1A2E',
  lightTextSecondary: '#6B6880',
};

export default {
  light: {
    text: palette.lightText,
    background: palette.lightBg,
    surface: palette.lightSurface,
    surfaceElevated: '#FAFAFA',
    border: palette.lightBorder,
    tint: palette.primary,
    accent: palette.primaryAlt,
    tabIconDefault: '#A0A0B0',
    tabIconSelected: palette.primary,
    textSecondary: palette.lightTextSecondary,
  },
  dark: {
    text: palette.text,
    background: palette.black,
    surface: palette.surface,
    surfaceElevated: palette.surfaceElevated,
    border: palette.border,
    tint: palette.primary,
    accent: palette.primaryAlt,
    tabIconDefault: palette.textMuted,
    tabIconSelected: palette.primary,
    textSecondary: palette.textSecondary,
  },
};

export { palette };
